title: Raghuveer Kona
logo: /assets/img/logo.png
description: Experienced Professional with 5 years as an Automation Developer and 3.5 years as an Entreprenuer. Currently working as a Product Manager.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
